// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportLogs(arg1, arg2) {
  return window['go']['main']['App']['ExportLogs'](arg1, arg2);
}

export function ImportLogs(arg1) {
  return window['go']['main']['App']['ImportLogs'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectSaveFileUri(arg1) {
  return window['go']['main']['App']['SelectSaveFileUri'](arg1);
}
