// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportLogs(arg1:string,arg2:string):Promise<void>;

export function ImportLogs(arg1:string):Promise<string>;

export function SelectFile():Promise<string>;

export function SelectSaveFileUri():Promise<string>;
